services:
  lisa:
    build:
      context: .
    container_name: runner-lisa
    restart: unless-stopped

    ports:
      - "2201:22"

    networks:
      - lisa_net

    volumes:
      - lisa_workspace:/workspace
      - lisa_hostkeys:/etc/ssh/hostkeys
      - ./ssh/authorized_keys:/config/authorized_keys:ro

    mem_limit: 2g
    cpus: 2
    pids_limit: 256

networks:
  lisa_net:
    driver: bridge

volumes:
  lisa_workspace:
  lisa_hostkeys:
  